name: NPM Publish

on:
  release:
    types:
      - published

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/publish-to-npm
        with:
          token: ${{ secrets.NPM_TOKEN }}
